version: "3"
services:
  question:
    build: .
    restart: always
    env_file:
      - .env
    labels:
      - traefik.http.routers.question.rule=Host(`q.shanyue.tech`)
      - traefik.http.routers.question.tls=true
      - traefik.http.routers.question.tls.certresolver=le
      - traefik.http.routers.qweb.rule=Host(`q.shanyue.tech`)
      - traefik.http.routers.qweb.entrypoints=web


networks:
  default:
    external:
      name: traefik_default
