version: "3"
services:
  question:
    build: .
    restart: always
    labels:
      - traefik.http.routers.question.rule=Host(`q.dev.shanyue.tech`)
      - traefik.http.routers.question.tls=true
      - traefik.http.routers.question.tls.certresolver=le

networks:
  default:
    external:
      name: traefik_default
